apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ArgoCD Sample App</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                margin: 0;
                padding: 20px;
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .container {
                background: white;
                padding: 40px;
                border-radius: 10px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.3);
                text-align: center;
                max-width: 600px;
            }
            h1 {
                color: #333;
                margin-bottom: 20px;
            }
            .info {
                background: #f8f9fa;
                padding: 20px;
                border-radius: 5px;
                margin: 20px 0;
            }
            .status {
                color: #28a745;
                font-weight: bold;
            }
            .version {
                color: #6c757d;
                font-size: 0.9em;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 ArgoCD Sample Application</h1>
            <p class="status">✅ Application is running successfully!</p>
            <div class="info">
                <h3>GitOps Status</h3>
                <p>This content is served from a ConfigMap mounted into the nginx pod.</p>
                <p>Any changes to this HTML in your Git repository will be automatically deployed by ArgoCD!</p>
            </div>
            <p class="version">Version: 1.0.0</p>
        </div>
    </body>
    </html>